version: '2'
services:
  sonos:
    build: ./sonos
    restart: always
    privileged: true
    network_mode: "host"
    expose:
      - "8000"
  fe:
    build: ./fe2
    restart: always
    network_mode: "host"
    expose:
      - "5000"
